### ISSUE TITLE
Error 127 - still having trouble finding the G++

### ISSUE THREAD

**Issue by kchurchwell** [metrumresearchgroup/mrgsolve#654] opened 2020-03-20 19:45 UTC
I've tried several times with different errors - all 127.

I know - .. this folder it's referencing does not exist:
/share/make/

R 3.6.3
RTools 3.5

> Sys.getenv("PATH")
[1] "C:\\Program Files\\NEW\\R\\R-3.6.3\\bin\\i386;C:\\Rtools\\mingw_64\\bin;C:\\Program Files\\IBM\\SPSS\\ModelerSubscription\\1.0\\ext\\bin\\spss.TMWBServer\\bin;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Rtools\\bin;C:\\Users\\K05048\\AppData\\Local\\Microsoft\\WindowsApps;"

> Sys.setenv(BINPREF64="C:\\Rtools\\mingw_64\\bin\\")
> Sys.setenv(BINPREF="C:\\Rtools\\mingw_64\\bin\\")
> mod <- mread("pk2", modlib())
Building pk2 ... error.

---:: stderr ::---------------------------------------------
sh: line 3: C:Rtoolsmingw_64bing++: command not found
make: *** [C:/PROGRA~1/NEW/R/R-36~1.3/share/make/winshlib.mk:13: pk2-mread-source.dll] Error 127
------------------------------------------------------------
NOTE: 'Error 127' was detected in the above message.
 This possibly indicates that the build toolchain
 could not be found. Please check for proper compiler 
 installation ('Rtools.exe' on Windows).  Also consider
 trying 'pkgbuild::check_build_tools(debug=TRUE)' to
 assist in diagnosing this issue.
------------------------------------------------------------ 
Error: the model build step failed.

> pkgbuild::find_rtools(debug=TRUE)
Scanning R CMD config CC...
cc_path:  
'' does not exist
Scanning path...
ls: C:\Rtools\bin\ls.exe 
gcc_path: C:\Rtools\mingw_64\bin\gcc.exe 
VERSION.txt
Rtools version 3.5.0.4 
Version: 3.5 
Found compatible gcc on path
[1] TRUE

>pkgbuild::check_build_tools(debug=TRUE)
Error: Could not find tools necessary to compile a package

**Comment by kylebaron** [comment] 2020-03-20 19:53
>Sys.setenv(BINPREF64="C:\Rtools\mingw_64\bin\")

In the path, either use double back slash or single front slash; eg

>Sys.setenv(BINPREF64="C:\\Rtools\\mingw_64\\bin\\")

**Comment by kylebaron** [comment] 2020-03-20 19:56
Note: I edited the post; it won't render correctly if reading in email.
`Sys.setenv(BINPREF64="C:\\Rtools\\mingw_64\\bin\\")`

**Comment by kchurchwell** [comment] 2020-03-20 20:55
Hi! THanks for helping.  

I think I'm closer but, I still can't get it to work:



> Sys.getenv("PATH")
[1] "C:\\Program Files\\NEW\\R\\R-3.6.3;c:\\Rtools\\bin;C:\\Program Files\\NEW\\R\\R-3.6.3\\bin\\i386;C:\\Program Files\\IBM\\SPSS\\ModelerSubscription\\1.0\\ext\\bin\\spss.TMWBServer\\bin;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Users\\K05048\\AppData\\Local\\Microsoft\\WindowsApps;"
> Sys.getenv("BINPREF")
[1] "c:\\Rtools\\mingw_64\\bin\\"
> Sys.getenv("BINPREF64")
[1] "c:\\Rtools\\mingw_64\\bin\\"
> library(mrgsolve)
> mod <- mread("pk2", modlib())
Building pk2 ... error.

---:: stderr ::---------------------------------------------
sh: -c: line 0: unexpected EOF while looking for matching `"'
sh: -c: line 1: syntax error: unexpected end of file
make: *** [C:/PROGRA~1/NEW/R/R-36~1.3/etc/i386/Makeconf:215: pk2-mread-source.o] Error 1
------------------------------------------------------------
Error: the model build step failed.
>

**Comment by kchurchwell** [comment] 2020-03-20 20:56
Hi! 

I think I'm closer, but, i'm still having problems.

> Sys.getenv("PATH")
[1] "C:\\Program Files\\NEW\\R\\R-3.6.3;c:\\Rtools\\bin;C:\\Program Files\\NEW\\R\\R-3.6.3\\bin\\i386;C:\\Program Files\\IBM\\SPSS\\ModelerSubscription\\1.0\\ext\\bin\\spss.TMWBServer\\bin;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Users\\K05048\\AppData\\Local\\Microsoft\\WindowsApps;"
> Sys.getenv("BINPREF")
[1] "c:\\Rtools\\mingw_64\\bin\\"
> Sys.getenv("BINPREF64")
[1] "c:\\Rtools\\mingw_64\\bin\\"
> library(mrgsolve)
> mod <- mread("pk2", modlib())
Building pk2 ... error.

---:: stderr ::---------------------------------------------
sh: -c: line 0: unexpected EOF while looking for matching `"'
sh: -c: line 1: syntax error: unexpected end of file
make: *** [C:/PROGRA~1/NEW/R/R-36~1.3/etc/i386/Makeconf:215: pk2-mread-source.o] Error 1
------------------------------------------------------------
Error: the model build step failed.
>

**Comment by kylebaron** [comment] 2020-03-20 22:45
Not sure what's going on, but the issue is with Rtools installation.  Maybe re-install from scratch?  Also ... what prompted you to set BINPREF?  It looks like Rtools is in the standard location.

**Comment by kylebaron** [comment] 2020-06-11 18:15
@kchurchwell Closing this; let me know if we can help with anything else.

**Closed by kylebaron** 2020-06-11 18:15 UTC
