### ISSUE TITLE
windows installation of the latest dev version fails

### ISSUE THREAD

**Issue by Wendy723** [metrumresearchgroup/mrgsolve#84] opened 2016-07-19 14:10 UTC
I have been trying to upgrade mrgsolve to match the development version, but it will not install using `devtools::install_github("metrumresearchgroup/mrgsolve", subdir="rdev"`. The installation cannot find the Rtools version and keeps asking to install Rtools when I already have it working with the correct paths.
If I revert back to the stable version using `devtools::install_github("metrumresearchgroup/mrgsolve@v0.6.0", subdir="rdev")`, installation is successful. Anything to do with the latest dev version?

**Comment by vjd** [comment] 2016-07-19 14:29
@Wendy723 did the stable version (0.6.0) install correctly? If not what was the final error that got printed out?

**Comment by Wendy723** [comment] 2016-07-19 14:35
The stable version did install correctly and can be loaded successfully. `Warning: Compile did not succeed. Returning NULL.``Warning message:
running command 'R CMD SHLIB  --preclean C:/Users/HECHUA~1/AppData/Local/Temp/RTMPMF~1/CFZ.cpp.cpp -o C:/Users/HECHUA~1/AppData/Local/Temp/RTMPMF~1/CFZ1b782278482b.dll' had status 1 ` was printed out when I tried to compile my model. I think the code itself has no problem.

**Comment by kylebmetrum** [comment] 2016-07-19 15:14
@Wendy723 There have been some changes in the `dev` version, but I have been testing on an (older) Windows environment without problems. 

Just to clarify: the `Warning: Compile did not succeed` error came from `0.6.0` right?  

One problem I did have was related to dependencies.  The `dev` version requires `dplyr 0.5.0` and `install_github` didn't really do that cleanly.  I ended up updating all of my packages (including `tibble` and all other packages that `dplyr` requires) before I got `install_github` to cleanly install `mrgsolve/dev` (actually, I just re-installed with `install.packages` ... but `update.packages` should get you the same thing).

Is there an install error message that you can share related to the `dev` version?  Where it was asking for `Rtools` again?

Also, can you share the `sessionInfo()` output ?

Finally, I pushed some changes to `dev` last night.  Can you try to install `dev` version again and report output from that?  I don't necessarily think that will fix the problems that you are having, but if we're going to debug this I'd like to make sure we're working on this new evolution.

I'm heading to the airport in an hour or so ... will be back on line this afternoon and can help more then.

Kyle

**Comment by kylebmetrum** [comment] 2016-07-19 15:15
Bumped version: 06b4c81

**Comment by kylebmetrum** [comment] 2016-07-19 16:58
@Wendy723 You might have seen a warning like this before:

```r
Could not find R program in PATH.
 If you are compiling your own models, please first make sure that
 the following command runs properly from your R prompt:
  system("R CMD SHLIB -v")
```

This used to be issued by `mrgsolve` if it couldn't find `R` in your system path.  I only recently started seeing this on Windows platform, but only when `R` tries a test loading of the package when it installs.  

The commit last night removed this warning and we use a different (more reliable) path to the `R` executable.  If you were seeing this warning, you shouldn't see it anymore the latest `dev` version.

**Comment by vjd** [comment] 2016-07-19 19:20
@kylebmetrum I tried to help @Wendy723. All dependencies are up to date based on a system update recently. So, that part is covered. There is no R message as you suggested. My understanding of where the problem lies is the following -
The Rtools got installed in the C drive as `Rbuildtools` directory. This is after a fresh install of Rtools3.3 (frozen). I think mrgsolve is looking for Rtools directory rather than Rbuildtools, but I may be stupidly wrong. Either way, if that was a problem, then packages like Rcpp and dplyr would have failed in the installation. Not sure what the problem is, will keep you posted

**Comment by kylebmetrum** [comment] 2016-07-19 19:22
Weird .... all of the sudden, I'm getting this on Ubuntu:


```r
> install_github("metrumresearchgroup/mrgsolve", subdir="rdev")
Downloading GitHub repo metrumresearchgroup/mrgsolve@master
from URL https://api.github.com/repos/metrumresearchgroup/mrgsolve/zipball/master
Error: Could not find build tools necessary to build mrgsolve
```

I haven't investigated yet, but I've never seen this before.

**Comment by kylebmetrum** [comment] 2016-07-19 19:26
@Wendy723 @vjd Can you re-install `devtools`?  I did new install and fixed that error from `install_github`.  

This is all new to me, but most of my testing has been on Windows with new devtools install.

**Comment by kylebmetrum** [comment] 2016-07-19 19:38
@vjd Did you ever find out what the error message actually was?   What exactly lead us to believe that something wasn't working?

**Comment by vjd** [comment] 2016-07-19 19:42
@kylebmetrum the issue is that installation never goes past the message that Rtools does not exist and it has to be installed. If you select yes then Rtools installation starts, but after completion of that installation, I did not take a look at the error message. I will ask @Wendy723 to capture this output and send it over.

**Comment by kylebmetrum** [comment] 2016-07-19 19:48
@vjd @Wendy723 Who is checking Rtools?  Seems like Rstudio getting involved here??

**Comment by kylebmetrum** [comment] 2016-07-19 19:48
BTW ... I'm upgrading to Rtools33 to see if I'm still working.

**Comment by Wendy723** [comment] 2016-07-19 19:50
I re-installed `devtools` and tried to install `mrgsolve`. `Downloading GitHub repo metrumresearchgroup/mrgsolve@master
from URL https://api.github.com/repos/metrumresearchgroup/mrgsolve/zipball/master
trying URL 'https://cran.rstudio.com/bin/windows/Rtools/Rtools33.exe'
Content type 'application/x-msdos-program' length 129680178 bytes (123.7 MB)
downloaded 123.7 MB

Error: Could not find build tools necessary to build mrgsolve` was print out, and Rstudio started to install rtools automatically even though rtools is already there.

**Comment by Wendy723** [comment] 2016-07-19 19:59
I re-installed `mrgsolve` using `devtools::install_github("metrumresearchgroup/mrgsolve", subdir="rdev", type="source")` ... did not see error printed out. But still have problem with compiling.

**Comment by vjd** [comment] 2016-07-19 20:00
@Wendy723 can you try installing in the regular RGui and not in Rstudio?

**Comment by kylebmetrum** [comment] 2016-07-19 20:01
Thanks, @Wendy723 .  I saw that same error. 

I upgraded to Rtools33, R 3.3.1 and re-installed everything without problem.  

@Wendy723  "But still have a problem with compiling."    How do you know there is a problem?  What is the problem?  What does that mean?


```r
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server 2008 R2 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] mrgsolve_0.6.1.9103 devtools_1.12.0    

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.6               digest_0.6.9             
 [3] dplyr_0.5.0               withr_1.0.2              
 [5] assertthat_0.1            R6_2.1.2                 
 [7] DBI_0.4-1                 git2r_0.15.0             
 [9] magrittr_1.5              httr_1.2.1               
[11] curl_0.9.7                lazyeval_0.2.0           
[13] RcppArmadillo_0.7.100.3.1 tools_3.3.1              
[15] memoise_1.0.0             tibble_1.1   

```

**Comment by Wendy723** [comment] 2016-07-19 20:15
`Compiling CFZ ... Error: There was a problem when compiling the model.` was reported.

**Comment by Wendy723** [comment] 2016-07-19 20:46
@kylebmetrum looks like a project directory issue. This does not happen when I run the house model

this is the error i get using `mread(...,ignore.stdout=FALSE)`

```
> mod <- mread("CFZ", code, ignore.stdout = FALSE)
Error in normalizePath(path.expand(path), winslash, mustWork) : path[1]="

$PARAM TVCL= 0.801, TVVc= 0.901, TVQ1= 0.431, TVVp1= 1.57, TVQ2= 1.61, TVVp2= 0.691 
TVF= 1, PMA= (10+7), PMA50= 13.1, Gamma= 1.91, BW= 8, OCC=1 

//gestational age= 10 months (40weeks)
//median postnatal age=7 months (from WHO growth chart) 

$SET delta=0.1, end=-1

$CMT CENT PERI1 PERI2

$MAIN
D_CENT = 0.17;
F_CENT = Fi;

double IOV = ETA(3);
if(OCC == 2) IOV = ETA(4);

double CLi = TVCL*(pow(PMA,Gamma)/(pow(PMA50,Gamma)+pow(PMA,Gamma)))*pow((BW/8.7), 0.75)*exp(ETA(1));
double Vci = TVVc*(BW/8.7)*exp(ETA(2));
double Q1i = TVQ1*pow((BW/8.7), 0.75);
double Vp1i = TVVp1*(BW/8.7);
double Q2i = TVQ2*pow((BW/8.7), 0.75);
double Vp2i = TVVp2*(BW/8.7);
double Fi = TVF*exp(IOV);

$ODE
double CP = CENT/Vci;

dxdt_CENT = - (CLi/Vci)*CENT - (Q1i/Vci)*CENT + (Q1i/Vp1i)*PERI1 +
(Q2i/Vp2i)*PERI2 - (Q2i/Vci)*CENT;
dxdt_PERI1 = (Q1i/Vci)*CENT - (Q1i/Vp1i)*PERI1; 
dxdt_PERI2 = (Q2i/Vci)*CENT - (Q2i/Vp2i)*PERI2; 



$OMEGA name = "bsv"
0 0

$OMEGA name = "bov"
0 0

$SIGMA
0

$TABLE
```

Even when I take out the `//` from the model, I get the following message.

```
> mod <- mread("CFZ", code, ignore.stdout = FALSE)
Error in normalizePath(path.expand(path), winslash, mustWork) : path[1]="

$PARAM TVCL= 0.801, TVVc= 0.901, TVQ1= 0.431, TVVp1= 1.57, TVQ2= 1.61, TVVp2= 0.691 
TVF= 1, PMA= (10+7), PMA50= 13.1, Gamma= 1.91, BW= 8, OCC=1 

$SET delta=0.1, end=-1

$CMT CENT PERI1 PERI2

$MAIN
D_CENT = 0.17;
F_CENT = Fi;

double IOV = ETA(3);
if(OCC == 2) IOV = ETA(4);

double CLi = TVCL*(pow(PMA,Gamma)/(pow(PMA50,Gamma)+pow(PMA,Gamma)))*pow((BW/8.7), 0.75)*exp(ETA(1));
double Vci = TVVc*(BW/8.7)*exp(ETA(2));
double Q1i = TVQ1*pow((BW/8.7), 0.75);
double Vp1i = TVVp1*(BW/8.7);
double Q2i = TVQ2*pow((BW/8.7), 0.75);
double Vp2i = TVVp2*(BW/8.7);
double Fi = TVF*exp(IOV);

$ODE
double CP = CENT/Vci;

dxdt_CENT = - (CLi/Vci)*CENT - (Q1i/Vci)*CENT + (Q1i/Vp1i)*PERI1 +
(Q2i/Vp2i)*PERI2 - (Q2i/Vci)*CENT;
dxdt_PERI1 = (Q1i/Vci)*CENT - (Q1i/Vp1i)*PERI1; 
dxdt_PERI2 = (Q2i/Vci)*CENT - (Q2i/Vp2i)*PERI2; 



$OMEGA name = "bsv"
0 0

$OMEGA name = "bov"
0 0

$SIGMA
0

$TABLE
table (CP) = CP;
table (DV) = CP*exp(EPS(1));
": The filename or extension is too long

```

**Comment by kylebmetrum** [comment] 2016-07-19 20:53
OIC ... This is the problem:


```r
mod <- mread("CFZ", code, ignore.stdout = FALSE)

```

The second argument is `project`, not `code`.  Fix it by using `mcode`:
```r
mod <- mcode("CFZ", code, ignore.stdout = FALSE)
```

or name the code argument to `mread`:
```r
mod <- mread("CFZ", code=code, ignore.stdout = FALSE)
```

Let me know if that works.  I will fix `mrgsolve` that that it always prints the error message when the compile doesn't work (that was a recent bug).

Kyle

**Comment by Wendy723** [comment] 2016-07-19 20:57
```
> mod <- mcode("CFZ", code=code, ignore.stdout = FALSE)
make: Nothing to be done for `all'.
Error: 

There was a problem when compiling the model.
> mod <- mread("CFZ", code=code, ignore.stdout = FALSE)
make: Nothing to be done for `all'.
Error: 

There was a problem when compiling the model.
```

**Comment by kylebmetrum** [comment] 2016-07-19 21:10
Ugh ... two more requests:
- what is the output of `sessionInfo()`
- try `mod <- mread("CFZ", code=code, ignore.stdout = FALSE,preclean=TRUE)`

**Comment by Wendy723** [comment] 2016-07-19 21:13
```
> session_info()
Session info ----------------------------------------------------------
 setting  value                       
 version  R version 3.3.1 (2016-06-21)
 system   x86_64, mingw32             
 ui       RStudio (0.99.484)          
 language (EN)                        
 collate  English_United States.1252  
 tz       America/New_York            
 date     2016-07-19                  

Packages --------------------------------------------------------------
 package       * version     date      
 assertthat      0.1         2013-12-06
 colorspace      1.2-6       2015-03-11
 curl            0.9.7       2016-04-10
 DBI             0.4-1       2016-05-08
 devtools      * 1.12.0      2016-06-24
 digest          0.6.9       2016-01-08
 dplyr         * 0.5.0       2016-06-24
 ggplot2       * 2.1.0       2016-03-01
 git2r           0.15.0      2016-05-11
 gtable          0.2.0       2016-02-26
 httr            1.2.1       2016-07-03
 installr      * 0.17.8      2016-05-14
 lazyeval        0.2.0       2016-06-12
 magrittr      * 1.5         2014-11-22
 MASS          * 7.3-45      2016-04-21
 memoise         1.0.0       2016-01-29
 mrgsolve      * 0.6.1.9103  2016-07-19
 munsell         0.4.3       2016-02-13
 PKPDmisc      * 0.4.3       2016-07-13
 plyr            1.8.4       2016-06-08
 purrr         * 0.2.2       2016-06-18
 R6              2.1.2       2016-01-26
 Rcpp            0.12.6      2016-07-19
 RcppArmadillo   0.7.100.3.1 2016-06-03
 scales          0.4.0       2016-02-26
 tibble          1.1         2016-07-04
 tidyr         * 0.5.1       2016-06-14
 withr           1.0.2       2016-06-20
 source                                       
 CRAN (R 3.3.1)                               
 CRAN (R 3.3.1)                               
 CRAN (R 3.3.1)                               
 CRAN (R 3.3.1)                               
 CRAN (R 3.3.1)                               
 CRAN (R 3.3.1)                               
 CRAN (R 3.3.1)                               
 CRAN (R 3.3.1)                               
 CRAN (R 3.3.0)                               
 CRAN (R 3.3.1)                               
 CRAN (R 3.3.1)                               
 CRAN (R 3.3.1)                               
 CRAN (R 3.3.1)                               
 CRAN (R 3.3.1)                               
 CRAN (R 3.3.1)                               
 CRAN (R 3.3.1)                               
 Github (metrumresearchgroup/mrgsolve@19f44d4)
 CRAN (R 3.3.1)                               
 Github (dpastoor/PKPDmisc@078a310)           
 CRAN (R 3.3.1)                               
 CRAN (R 3.3.1)                               
 CRAN (R 3.3.1)                               
 CRAN (R 3.3.1)                               
 CRAN (R 3.3.1)                               
 CRAN (R 3.3.1)                               
 CRAN (R 3.3.1)                               
 CRAN (R 3.3.1)                               
 CRAN (R 3.3.1)                        

```

```
> mod <- mread("CFZ", code=code, ignore.stdout = FALSE,preclean = TRUE)
make: Nothing to be done for `all'.
Error: 

There was a problem when compiling the model.
```

**Comment by kylebmetrum** [comment] 2016-07-19 21:21
Thanks.   Not sure where to go next ... I have the model running on mac, windows, ubuntu and they all work.  Let's set up a call to debug `mread`.  I'll talk to @vjd

**Comment by Wendy723** [comment] 2016-07-19 21:23
Thanks!

**Comment by kylebmetrum** [comment] 2016-07-19 21:34
Sorry we couldn't figure it out yet.  I was changing some code that might be relevant to this issue, but unfortunately I can reproduce it even after matching your environment (as best as I can).  I can't think of a scenario where I'd expect to see what you are seeing so I don't have a great idea of what to try / suggest next. 

We can debug it together when we get a chance.  

If you're feeling an advanture and want to get into it on your own, you can try (in rstudio):

```r
debug(mrgsolve)
mod <- mcode("CFZ", code)
```

Keep going until you get to this area:
https://github.com/metrumresearchgroup/mrgsolve/blob/master/rdev/R/modspec.R#L467-L498

**Comment by dpastoor** [comment] 2016-07-20 02:01
@Wendy723 

Let's back up a second to make sure things can actually be reproduced. What is _exactly_ the setup you are using. Are you using inline definitions, or saving a separate .cpp file to contain the model code?

please paste the (entire) code you have been using, including libraries loading, etc. 

Second, have you tried compiling one of the simpler models available in the examples? Do those also fail? Are the errors the same?

**Comment by kylebmetrum** [comment] 2016-07-20 02:10
@dpastoor 

I think it can be pieced together here
https://github.com/metrumresearchgroup/mrgsolve/issues/84#issuecomment-233760391

and here
https://github.com/metrumresearchgroup/mrgsolve/issues/84#issuecomment-233767791

The `dev` version has been a bit of a moving target in the last couple of days.  I just merged another PR that straightens out one issue.   However I don't think it can totally explain what's going on.

**Comment by Wendy723** [comment] 2016-07-20 03:26
@dpastoor below is the entire code and print out.
```
> library(MASS)
> library(dplyr)
> library(purrr)
> library(tidyr)
> library(ggplot2)
> library(PKPDmisc)
> library(mrgsolve)
> library(magrittr)
> 
> 
> ggtheme <- function(){
+         theme_bw()+
+                 theme(axis.text=element_text(face="bold",size=12))+
+                 theme(axis.title=element_text(face="bold",size=16))+
+                 theme(legend.position="")+
+                 theme(strip.text.x = element_text(face="bold",size=14))+
+                 theme(strip.text.y = element_text(face="bold",size=14))+
+                 theme(plot.title = element_text(size=16, face="bold"))
+ }
> 
> 
> 
> code <- '
+ $PARAM TVCL= 0.801, TVVc= 0.901, TVQ1= 0.431, TVVp1= 1.57, TVQ2= 1.61, TVVp2= 0.691, 
+ TVF= 1, PMA= (10+7), PMA50= 13.1, Gamma= 1.91, BW= 8, OCC=1 
+ 
+ $SET delta=0.1, end=-1
+ 
+ $CMT CENT PERI1 PERI2
+ 
+ $MAIN
+ D_CENT = 0.17;
+ 
+ F_CENT = Fi;
+ 
+ double IOV = ETA(3);
+ if(OCC == 2) IOV = ETA(4);
+ 
+ double CLi = TVCL*(pow(PMA,Gamma)/(pow(PMA50,Gamma)+pow(PMA,Gamma)))*pow((BW/8.7), 0.75)*exp(ETA(1));
+ double Vci = TVVc*(BW/8.7)*exp(ETA(2));
+ double Q1i = TVQ1*pow((BW/8.7), 0.75);
+ double Vp1i = TVVp1*(BW/8.7);
+ double Q2i = TVQ2*pow((BW/8.7), 0.75);
+ double Vp2i = TVVp2*(BW/8.7);
+ double Fi = TVF*exp(IOV);
+ 
+ $ODE
+ double CP = CENT/Vci;
+ 
+ dxdt_CENT = - (CLi/Vci)*CENT - (Q1i/Vci)*CENT + (Q1i/Vp1i)*PERI1 +
+ (Q2i/Vp2i)*PERI2 - (Q2i/Vci)*CENT;
+ dxdt_PERI1 = (Q1i/Vci)*CENT - (Q1i/Vp1i)*PERI1; 
+ dxdt_PERI2 = (Q2i/Vci)*CENT - (Q2i/Vp2i)*PERI2; 
+ 
+ 
+ 
+ $OMEGA name = "bsv"
+ 0 0
+ 
+ $OMEGA name = "bov"
+ 0 0
+ 
+ $SIGMA
+ 0
+ 
+ $TABLE
+ table (CP) = CP;
+ table (DV) = CP*exp(EPS(1));
+ '
> 
> mod <- mread("CFZ", code=code, ignore.stdout=FALSE, preclean=TRUE)
make: Nothing to be done for `all'.
Error: 

There was a problem when compiling the model.

```

When I tried the demo, same error was print out.
```
> code <- '
+ $GLOBAL
+ #define CP (CENT/VC)
+ #define INH (CP/(IC50+CP))
+ 
+ $SET delta=0.1
+ 
+ $PARAM TVCL=1, TVVC=20, KA = 1.3, KIN=100, KOUT=2, IC50=10
+ 
+ $CMT GUT, CENT, RESP
+ 
+ $MAIN
+ double CL = exp(log(TVCL) + ETA(1));
+ double VC = exp(log(TVVC) + ETA(2));
+ 
+ RESP_0 = KIN/KOUT;
+ 
+ $OMEGA 0 0
+ 
+ $ODE
+ dxdt_GUT = -KA*GUT;
+ dxdt_CENT = KA*GUT - (CL/VC)*CENT;
+ dxdt_RESP = KIN*(1-INH) - KOUT*RESP;
+ 
+ $CAPTURE CP
+ '
> 
> mod <- mcode("demo", code)
Compiling demo ... Error: 

There was a problem when compiling the model.
```

**Comment by kylebmetrum** [comment] 2016-07-20 15:48
@Wendy723 can you please email me about a brief discussion of this issue? https://github.com/kylebmetrum

**Closed** 2016-09-28 18:37 UTC
