### ISSUE TITLE
Error When CMT Annotation Contains Equal Sign

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/mrgsolve#576] opened 2019-10-18 00:50 UTC
I had considered everything after the last colon in an annotation to be free text, but there appears to be an error including an equal sign there.  I cannot run `mread()` on this model without error:

```r
> mod_test <- mread_cache(model="foobar", file="popex.Rmd")
Error in parse(text = paste0("list(", x, ")")) : 
  <text>:1:16: unexpected '='
1: list(BAR : baz =
                   ^
```
[popex.txt](https://github.com/metrumresearchgroup/mrgsolve/files/3741821/popex.txt)

**Comment by kylebaron** [comment] 2019-10-18 01:14
@billdenney Thanks for the report.

**Comment by kylebaron** [comment] 2019-10-18 01:15
Internal: the issue is in scrape_opts; picking up on `=` as indicating an option.

**Comment by kylebaron** [comment] 2019-10-18 01:22
``` r
library(mrgsolve)
#> 
#> Attaching package: 'mrgsolve'
#> The following object is masked from 'package:stats':
#> 
#>     filter

code <- c(
"FOO : bar",
"BAR : baz =  zot"
)

try(mrgsolve:::scrape_opts(code, narrow=FALSE))
#> Error in parse(text = paste0("list(", x, ")")) : 
#>   <text>:1:16: unexpected '='
#> 1: list(BAR : baz =
#>                    ^

try(mrgsolve:::scrape_opts(code, narrow=TRUE))
#> $x
#> [1] "FOO : bar"        "BAR : baz =  zot"
```

<sup>Created on 2019-10-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by kylebaron** [comment] 2019-10-27 01:57
```
> code <- '
+ [ cmt ] 
+ foo : bar = 10
+ 
+ '
> 
> mcode("foo", code)
 Error in parse(text = paste0("list(", x, ")")) : 
  <text>:1:16: unexpected '='
1: list(foo : bar =
                   ^ 
```

**Comment by kylebaron** [comment] 2019-10-27 01:59
```
> code <- '
+ [ cmt ] @annotated
+ foo : bar = 10
+ 
+ '
> 
> mcode("foo", code)
Building foo ... done.


-----------------  source: foo.cpp  -----------------

  project: /private/var/fol.../T/RtmpUrRVWG
  shared object: foo-so-1782d208a22d 

  time:          start: 0 end: 24 delta: 1
                 add: <none>

  compartments:  foo [1]
  parameters:    <none>
  captures:       <none>
  omega:         0x0 
  sigma:         0x0 

  solver:        atol: 1e-08 rtol: 1e-08 maxsteps: 20k
------------------------------------------------------
> 
```

**Comment by kylebaron** [comment] 2019-10-27 02:16
Closing this for #578

**Closed by kylebaron** 2019-10-27 02:16 UTC
Labels: bug, bug-fixed
