### ISSUE TITLE
[Question] Problem finding time of first dose?

### ISSUE THREAD

**Issue by nguyenjq** [metrumresearchgroup/mrgsolve#383] opened 2018-07-19 21:13 UTC
Hello again,

I have a simple two compartment model with first order absorption that I am trying to simulate from. I received a very strange error message and was hoping to get some clarification.

```
> out <- 
+   mod %>%
+   zero_re %>% 
+   data_set(full) %>% 
+   carry_out(C, ID, AGE, TIME, AMT, MDV, EVID) %>% 
+   mrgsim(tad = TRUE) %>% 
+   as.data.frame
Dropping non-numeric columns: C CONC DV WT 
Error: There was a problem finding time of first dose.
```

Below is a sample of what the data looks like 

```

C | ID | SUBJ  | DOSE | TIME | CONC | DV    | AMT | EVID | MDV | AGE | CMT

. | 1  | 10001 | 20   | 0    | .    | .     | 20  | 1    | 1   | 55  | 1
. | 1  | 10001 | 20   | 0.5  | 10.8 | 2.857 | 0   | 0    | 0   | 55  | 2
. | 1  | 10001 | 20   | 1    | 74.2 | 3.259 | 0   | 0    | 0   | 55  | 2
. | 1  | 10001 | 20   | 1.5  | 95   | 3.313 | 0   | 0    | 0   | 55  | 2
. | 1  | 10001 | 20   | 2    | 61.4 | 3.217 | 0   | 0    | 0   | 55  | 2
. | 1  | 10001 | 20   | 3    | 66   | 3.233 | 0   | 0    | 0   | 55  | 2
. | 1  | 10001 | 20   | 4    | 19.2 | 2.97  | 0   | 0    | 0   | 55  | 2
. | 1  | 10001 | 20   | 6    | 26.7 | 3.038 | 0   | 0    | 0   | 55  | 2
. | 1  | 10001 | 20   | 8    | 24.3 | 3.018 | 0   | 0    | 0   | 55  | 2
. | 1  | 10001 | 20   | 12   | 14.7 | 2.916 | 0   | 0    | 0   | 55  | 2
. | 1  | 10001 | 20   | 24   | 14   | 2.907 | 0   | 0    | 0   | 55  | 2
. | 1  | 10001 | 20   | 48   | 11.4 | 2.866 | 0   | 0    | 0   | 55  | 2
. | 1  | 10001 | 20   | 72   | 7.2  | 2.784 | 0   | 0    | 0   | 55  | 2
. | 1  | 10001 | 20   | 96   | 2.9  | 2.127 | 0   | 0    | 0   | 55  | 2
```

Thank you!
Jenny

**Comment by kylebmetrum** [comment] 2018-07-20 14:06
Can you try `tad = FALSE` and let me know what happens?

**Comment by kylebmetrum** [comment] 2018-07-20 14:16
Also ... what version are you using?

Here's what I'm getting with your example:

``` r
library(mrgsolve)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

full <- tribble(
~C , ~ID , ~SUBJ  , ~DOSE , ~TIME , ~CONC , ~DV    , ~AMT , ~EVID , ~MDV , ~AGE , ~CMT,
"." , 1  , 10001 , 20   , 0    , "."    , "."     , 20  , 1    , 1   , 55  , 1,
"." , 1  , 10001 , 20   , 0.5  , 10.8 , 2.857 , 0   , 0    , 0   , 55  , 2,
"." , 1  , 10001 , 20   , 1    , 74.2 , 3.259 , 0   , 0    , 0   , 55  , 2,
"." , 1  , 10001 , 20   , 1.5  , 95   , 3.313 , 0   , 0    , 0   , 55  , 2,
"." , 1  , 10001 , 20   , 2    , 61.4 , 3.217 , 0   , 0    , 0   , 55  , 2,
"." , 1  , 10001 , 20   , 3    , 66   , 3.233 , 0   , 0    , 0   , 55  , 2,
"." , 1  , 10001 , 20   , 4    , 19.2 , 2.97  , 0   , 0    , 0   , 55  , 2,
"." , 1  , 10001 , 20   , 6    , 26.7 , 3.038 , 0   , 0    , 0   , 55  , 2,
"." , 1  , 10001 , 20   , 8    , 24.3 , 3.018 , 0   , 0    , 0   , 55  , 2,
"." , 1  , 10001 , 20   , 12   , 14.7 , 2.916 , 0   , 0    , 0   , 55  , 2,
"." , 1  , 10001 , 20   , 24   , 14   , 2.907 , 0   , 0    , 0   , 55  , 2,
"." , 1  , 10001 , 20   , 48   , 11.4 , 2.866 , 0   , 0    , 0   , 55  , 2,
"." , 1  , 10001 , 20   , 72   , 7.2  , 2.784 , 0   , 0    , 0   , 55  , 2,
"." , 1  , 10001 , 20   , 96   , 2.9  , 2.127 , 0   , 0    , 0   , 55  , 2
)

full
#> # A tibble: 14 x 12
#>    C        ID  SUBJ  DOSE  TIME CONC  DV      AMT  EVID   MDV   AGE   CMT
#>    <chr> <dbl> <dbl> <dbl> <dbl> <chr> <chr> <dbl> <dbl> <dbl> <dbl> <dbl>
#>  1 .         1 10001    20   0   .     .        20     1     1    55     1
#>  2 .         1 10001    20   0.5 10.8  2.857     0     0     0    55     2
#>  3 .         1 10001    20   1   74.2  3.259     0     0     0    55     2
#>  4 .         1 10001    20   1.5 95    3.313     0     0     0    55     2
#>  5 .         1 10001    20   2   61.4  3.217     0     0     0    55     2
#>  6 .         1 10001    20   3   66    3.233     0     0     0    55     2
#>  7 .         1 10001    20   4   19.2  2.97      0     0     0    55     2
#>  8 .         1 10001    20   6   26.7  3.038     0     0     0    55     2
#>  9 .         1 10001    20   8   24.3  3.018     0     0     0    55     2
#> 10 .         1 10001    20  12   14.7  2.916     0     0     0    55     2
#> 11 .         1 10001    20  24   14    2.907     0     0     0    55     2
#> 12 .         1 10001    20  48   11.4  2.866     0     0     0    55     2
#> 13 .         1 10001    20  72   7.2   2.784     0     0     0    55     2
#> 14 .         1 10001    20  96   2.9   2.127     0     0     0    55     2

glimpse(full)
#> Observations: 14
#> Variables: 12
#> $ C    <chr> ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", "....
#> $ ID   <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
#> $ SUBJ <dbl> 10001, 10001, 10001, 10001, 10001, 10001, 10001, 10001, 1...
#> $ DOSE <dbl> 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20
#> $ TIME <dbl> 0.0, 0.5, 1.0, 1.5, 2.0, 3.0, 4.0, 6.0, 8.0, 12.0, 24.0, ...
#> $ CONC <chr> ".", "10.8", "74.2", "95", "61.4", "66", "19.2", "26.7", ...
#> $ DV   <chr> ".", "2.857", "3.259", "3.313", "3.217", "3.233", "2.97",...
#> $ AMT  <dbl> 20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
#> $ EVID <dbl> 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
#> $ MDV  <dbl> 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
#> $ AGE  <dbl> 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55
#> $ CMT  <dbl> 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2

mod <- mread("pk2", modlib())
#> Compiling pk2 ...
#> done.

out <- 
   mod %>%
   zero_re %>% 
   data_set(full) %>% 
   carry_out(C, ID, AGE, TIME, AMT, MDV, EVID) %>% 
   mrgsim(tad = TRUE) 
#> Dropping non-numeric columns: C CONC DV

out
#> Model:  pk2 
#> Dim:    14 x 11 
#> Time:   0 to 96 
#> ID:     1 
#>      ID TIME tad EVID AMT AGE MDV       EV   CENT PERIPH     CP
#> [1,]  1  0.0 0.0    1  20  55   1 20.00000  0.000 0.0000 0.0000
#> [2,]  1  0.5 0.5    0   0  55   0 12.13061  7.565 0.2006 0.3782
#> [3,]  1  1.0 1.0    0   0  55   0  7.35759 11.642 0.6506 0.5821
#> [4,]  1  1.5 1.5    0   0  55   0  4.46260 13.671 1.1978 0.6835
#> [5,]  1  2.0 2.0    0   0  55   0  2.70671 14.512 1.7581 0.7256
#> [6,]  1  3.0 3.0    0   0  55   0  0.99574 14.485 2.7645 0.7243
#> [7,]  1  4.0 4.0    0   0  55   0  0.36631 13.636 3.5390 0.6818
#> [8,]  1  6.0 6.0    0   0  55   0  0.04958 11.772 4.4516 0.5886

plot(out)
```

![](https://i.imgur.com/qOMa1N6.png)

Created on 2018-07-20 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by nguyenjq** [comment] 2018-07-23 03:43
Hi Kyle,

(1) Removing TAD allowed the simulation to proceed.
(2) I have mrgsolve 0.8.12 using R 3.5.0

Since it seems to be working on your end, is it due to having an older version? What was happening that caused that error to arise?

**Comment by kylebmetrum** [comment] 2018-07-23 11:56
Hi @nguyenjq - 

We're using the same version of mrgsolve and R.  I'm trying to get us running the same bit of code and get the same results.  At that point we might be able to figure out what is going on.

Did you try the code that I posted to see if you still see the issue?

`Dropping non-numeric columns: C CONC DV WT `

I noticed `WT` here but it wasn't in the sample data set that you shared.  What other columns are in the data?  In order to reproduce, it would be helpful to have that object.  Maybe try

```
save.image(file = "session.txt")
```

and post the `session.txt` file.  Warning that every object in your R session will be included in that file.  If that's an issue (a lot of stuff in your R session that you don't want to share with the world), try

```
save(file = "session.txt", list = c("full", "mod", "out"))
```

Thanks,
Kyle

**Comment by nguyenjq** [comment] 2018-08-03 16:11
Hi Kyle,

My apologies for the delay in response. I tried your code snippet and it worked fine, both with the pk2 model and the original model I was working with. `WT` is not relevant in the model I have so it is fine to drop. I ended up dropping the `tad` option from `mrgsim()` because I later realised it was not necessary for what I was doing.

As it currently stands, if I run the full dataset with my model file with the `tad=TRUE` option, I'm still seeing the same error. There are additional columns in the dataset, but they are not relevant for the model and so are dropped. The sample dataset I posted above only contained the mandatory columns needed for the model. I subsetted the full dataset with the same columns that I provided to you in the sample data above and still run into that error.

I'm unsure if I can share with you the full dataset and model file so let me see what I can do for you to reproduce the error and understand what is happening. 

Thanks for following up, I really appreciate it and have found this tool to be very useful for me. 

Jenny

**Comment by kylebmetrum** [comment] 2018-08-03 17:00
Thanks for reporting back.  I'll close then as it seems like we're getting different behavior (works for me but not for you).  I'd like to be able to track down the discrepancy, but will not be able to do it since we cannot reproduce.  Please feel free to open again if you ever want to pursue this further.

Best Regards,
Kyle

**Comment by nguyenjq** [comment] 2018-08-06 23:09
Hi Kyle,

I tried to run the code snippet you had earlier to save the session info, but it comes out as a jumble of symbols which I don't think you're looking for. 

I'm able to provide you with the file and model I have been using that has been giving me this error if you can direct me to a place where I can send it for you to inspect. 

Best,
Jenny

**Comment by kylebmetrum** [comment] 2018-08-07 00:07
Hi Jenny - 

If you can send something to the email address here:
https://github.com/kylebmetrum

I'd be happy to give it a try.  Maybe you've moved on, but if there is an issue here, I'd really like to figure it out so we can determine where the bug is and get it fixed if it is in mrgsolve.

Thanks,
Kyle

**Comment by kylebmetrum** [comment] 2018-08-07 20:19
This ended up being an individual with an observation, but no dosing records.  I talked with Jenny about this.  Not clear if there should be an error in this case or no.  Definitely could imagine a mixed data set where there were some folks with PK/PD and some with just PD.  But generating an error in this case was helpful in that it signaled a problem. The signal would be better if there was an ID associated with the error message.  I'll start that in another issue.  But I think it will keep erroring for now, until there is a clear way forward. 

Thanks @nguyenjq for the report and for sending the data set.

**Closed by kylebmetrum** 2018-08-07 20:19 UTC
